# Netlify deployment configuration for FireSight

[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300" 